### ISSUE TITLE
Location of Folder and access

### ISSUE THREAD

**Issue by drops77** [Philippe734/Simple.NFS.GUI#10]
Thank you for your program works great!!!

When i completed the GUI it created the folder in the root of the system in /media/
i named my folder NAS so it outputted to 
/media/NAS

wondering if its possible to have an option where the user can choose the location. Either to specify the location of it, or navigate to it and give the current user permission to access it.

I had to chmod -R 777 the folder to be able to access it.

**Comment by Philippe734** [comment]
Sorry, I'm afraid to not do it.
