### ISSUE TITLE
dpkg: dependency problems prevent configuration of simple-nfs-gui:

### ISSUE THREAD

**Issue by SISolutions** [Philippe734/Simple.NFS.GUI#13]
Trying to install it to ubuntu 16.04.5

sudo dpkg -i ~/Downloads/Setup_Simple_NFS_GUI_1.0.9.deb && sudo apt-get install -fy
Selecting previously unselected package simple-nfs-gui.
(Reading database ... 359113 files and directories currently installed.)
Preparing to unpack .../Setup_Simple_NFS_GUI_1.0.9.deb ...
Unpacking simple-nfs-gui (1.0.14-0ubuntu1) ...
dpkg: dependency problems prevent configuration of simple-nfs-gui:
 simple-nfs-gui depends on gambas3-runtime (>= 3.9); however:
  Package gambas3-runtime is not installed.
 simple-nfs-gui depends on gambas3-runtime (<< 3.99.0); however:
  Package gambas3-runtime is not installed.
 simple-nfs-gui depends on gambas3-gb-image (>= 3.9); however:
  Package gambas3-gb-image is not installed.
 simple-nfs-gui depends on gambas3-gb-image (<< 3.99.0); however:
  Package gambas3-gb-image is not installed.
 simple-nfs-gui depends on gambas3-gb-gtk3 (>= 3.9); however:
  Package gambas3-gb-gtk3 is not installed.
 simple-nfs-gui depends on gambas3-gb-gtk3 (<< 3.99.0); however:
  Package gambas3-gb-gtk3 is not installed.
 simple-nfs-gui depends on gambas3-gb-form (>= 3.9); however:
  Package gambas3-gb-form is not installed.
 simple-nfs-gui depends on gambas3-gb-form (<< 3.99.0); however:
  Package gambas3-gb-form is not installed.

dpkg: error processing package simple-nfs-gui (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.22-1ubuntu5.2) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1.1) ...
Errors were encountered while processing:
 simple-nfs-gui

**Comment by Philippe734** [comment]
As explains in the main page, you need to add the dependencies. Here, comamnd to install in single line:

`sudo add-apt-repository ppa:gambas-team/gambas3 -y && sudo apt-get update && sudo dpkg -i ~/Downloads/Setup_Simple_NFS_GUI_1.0.9.deb && sudo apt-get install -fy && sudo simple-nfs-gui`

**Comment by SISolutions** [comment]
Yep found the solution but didn't have time to post it to git.

Very bizzare this very useful gui doesn't exist natively in all distros.
Really very strange and stupid from the side of distro devs.
