### ISSUE TITLE
Add packages Fedora

### ISSUE THREAD

**Issue by specialworld83** [Philippe734/Simple.NFS.GUI#14]
Good morning, I packaged the fedora software 29. Here the [url](https://www.codelinsoft.it/sito/blog/176-facile-condivisione-nfs-con-la-semplice-interfaccia-grafica-nfs-server-e-client.html)

Package: [https://repository.codelinsoft.it/?dir=fedora/29](https://repository.codelinsoft.it/?dir=fedora/29)

**Comment by Philippe734** [comment]
Thanks! I add the link to my main page.
