### ISSUE TITLE
Failed to mount/timed out

### ISSUE THREAD

**Issue by SimonDedman** [Philippe734/Simple.NFS.GUI#15]
Hi Philippe,

I added a folder as client+server from machine 1 and added that as client on machine 2. The folder is now automatically displayed on machine 1 as a network folder (192.168.etc.etc:/path) but I can't mount it ("Failed to mount: access denied", even as root) and I don't know why I'd want to (unless it has to be here to be visible to the client).

In the client, I try to mount as user or root and it times out.

Subsequently I cannot do anything. Please let me know if you have any ideas.

Thanks.

**Comment by Philippe734** [comment]
Difficult to help you. It depends of your system, folders shared, network... Check yourself with guide about NFS:
https://help.ubuntu.com/community/SettingUpNFSHowTo
https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nfs-mount-on-ubuntu-18-04
https://www.jbnet.fr/systeme/linux/linux-ubuntu-server-18-04-nfs-client-server.html
