### ISSUE TITLE
Seg Fault on 18.04

### ISSUE THREAD

**Issue by shadowbq** [Philippe734/Simple.NFS.GUI#16]
Dont waste your time...
```
sudo add-apt-repository ppa:gambas-team/gambas-daily
sudo apt install gambas3-gb-gtk3
sudo dpkg -i Setup_Simple_NFS_GUI_1.0.9.deb

sudo -H Simple_NFS_GUI 
Segmentation fault
```

**Comment by Philippe734** [comment]
v 1.0.9 tested in fresh install of 18.04 in virtualbox, no issue observed. Yet, I switch from GTK3 to Qt4. Here the one line commands:
`sudo add-apt-repository ppa:gambas-team/gambas3 -y ; sudo apt-get update ; wget https://github.com/Philippe734/Simple.NFS.GUI/raw/master/Linux/1.0.15/simple-nfs-gui_1.0.15-0ubuntu1_all.deb -P ~ ; sudo dpkg -i ~/simple-nfs-gui_1.0.15-0ubuntu1_all.deb ; sudo apt-get install -fy ; rm ~/simple-nfs-gui_1.0.15-0ubuntu1_all.deb ; sudo -H Simple_NFS_GUI`
