### ISSUE TITLE
GUI is empty even when launching it as a super suer 

### ISSUE THREAD

**Issue by BuckZ57** [Philippe734/Simple.NFS.GUI#17]
![image](https://user-images.githubusercontent.com/61523248/78936508-b639dc00-7a7c-11ea-946f-533f1fb08a02.png)

#lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by Philippe734** [comment]
Please, use the following commands to downloads, install and run the program:
`sudo add-apt-repository ppa:gambas-team/gambas3 -y ; sudo apt-get update ; wget https://github.com/Philippe734/Simple.NFS.GUI/raw/master/Linux/1.0.15/simple-nfs-gui_1.0.15-0ubuntu1_all.deb -P ~ ; sudo dpkg -i ~/simple-nfs-gui_1.0.15-0ubuntu1_all.deb ; sudo apt-get install -fy ; rm ~/simple-nfs-gui_1.0.15-0ubuntu1_all.deb ; sudo -H Simple_NFS_GUI`
