### ISSUE TITLE
No right IP address in Select the Server

### ISSUE THREAD

**Issue by wolfvms** [Philippe734/Simple.NFS.GUI#20]
When pressing ... button I receive the following IP address 169.254.10.191 It is not the right IP address of my NAS server which I want mounting. Linux Mint 18.3 Cinnamon edition.

**Comment by goldphnx** [comment]
I have the same issue. It gives 169.254.167.25 It would be great to be able to manually input the IP address.

**Comment by Philippe734** [comment]
Servers and clients must have static IP addresses
