### ISSUE TITLE
How to set this app to use gambas3-gb-qt5 instead of gambas3-gb-qt4 for ubuntu 20.04?

### ISSUE THREAD

**Issue by kocoman1** [Philippe734/Simple.NFS.GUI#21]
How to set this app to use gambas3-gb-qt5 instead of gambas3-gb-qt4 for ubuntu 20.04?

**Comment by registered-to-post-this** [comment]
Download and extract simple-nfs-gui_1.0.15.orig.tar.gz
`add-apt-repository ppa:gambas-team/gambas-daily`
`apt install gambas3`
Start gambas3
Open project (simple-nfs-gui_1.0.15.orig/src/Simple_NFS_GUI) - it will complain about a class missing, ignore that
Right click Simple_NFS_Gui, click Properties
Go to Components, uncheck gb.qt4 and check gb.qt5. Click ok.
Project > Make > Installation package

The .deb it creates should be usable now.

**Comment by LatverianDictator** [comment]
Tried that on a new install of Linux Mint 20. Nada.
Do not know how to code hence the tool and instructions were perfect for a noob like myself.
Is there going to be a fix to make this work for Linux Mint 20?

**Comment by Philippe734** [comment]
#23

**Comment by Philippe734** [comment]
#23

**Comment by Philippe734** [comment]
I will further more about install on 20.04

**Comment by Philippe734** [comment]
I issued two releases with different GUI. Please, try it and tell for each what.
Release with GTK3 GUI (works with Ubuntu 20.04):
  ```
  sudo add-apt-repository ppa:gambas-team/gambas3 -y && sudo apt-get update && wget https://github.com/Philippe734/Simple.NFS.GUI/raw/master/Linux/1.0.16/simple-nfs-gui_1.0.16-0ubuntu1_all.deb -P ~ && sudo dpkg -i ~/simple-nfs-gui_1.0.16-0ubuntu1_all.deb && sudo apt-get install -fy && rm ~/simple-nfs-gui_1.0.16-0ubuntu1_all.deb && sudo -H Simple_NFS_GUI
  ```
Release with Qt5 GUI (I don't know were it works, tell me in an issue):
  ```
  sudo add-apt-repository ppa:gambas-team/gambas3 -y && sudo apt-get update && wget https://github.com/Philippe734/Simple.NFS.GUI/raw/master/Linux/1.0.17/simple-nfs-gui_1.0.17-0ubuntu1_all.deb -P ~ && sudo dpkg -i ~/simple-nfs-gui_1.0.17-0ubuntu1_all.deb && sudo apt-get install -fy && rm ~/simple-nfs-gui_1.0.17-0ubuntu1_all.deb && sudo -H Simple_NFS_GUI
  ```

**Comment by Philippe734** [comment]
Fixed with the latest release as AppImage
