### ISSUE TITLE
Multiples errors when running sudo Simple_NFS_GUI, it doesn't start

### ISSUE THREAD

**Issue by guy-teube** [Philippe734/Simple.NFS.GUI#22]
Hello,

I use Ubuntu 18.04 LTS, up-to-date.
I have installed the program Simple_NFS_GUI, following the [documentation](https://github.com/Philippe734/Simple.NFS.GUI#install).

Then, I run :
$ sudo Simple_NFS_GUI
or
$ sudo -H Simple_NFS_GUI

The application begins to start (I see the window appears), but it crashes before to be displayed : 
https://pic.infini.fr/lWewngvm/j4pXaA6a.png

The logs : 
guy@ubuntu:~$ sudo Simple_NFS_GUI 
[sudo] Mot de passe de guy : 
X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x13d
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0x2800016
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2800017
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2800017
^C
guy@ubuntu:~$ sudo -H Simple_NFS_GUI
X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x13d
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0x5200016
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x5200017
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x5200017
^C

Thank you for your help.

**Comment by Philippe734** [comment]
Install is ok on 18.04, please see here the log:
https://github.com/Philippe734/Simple.NFS.GUI/issues/18

**Comment by Philippe734** [comment]
Try :
Release with GTK3 GUI (works with Ubuntu 20.04):
  ```
  sudo add-apt-repository ppa:gambas-team/gambas3 -y && sudo apt-get update && wget https://github.com/Philippe734/Simple.NFS.GUI/raw/master/Linux/1.0.16/simple-nfs-gui_1.0.16-0ubuntu1_all.deb -P ~ && sudo dpkg -i ~/simple-nfs-gui_1.0.16-0ubuntu1_all.deb && sudo apt-get install -fy && rm ~/simple-nfs-gui_1.0.16-0ubuntu1_all.deb && sudo -H Simple_NFS_GUI
  ```
Release with Qt5 GUI (I don't know were it works, tell me in an issue):
  ```
  sudo add-apt-repository ppa:gambas-team/gambas3 -y && sudo apt-get update && wget https://github.com/Philippe734/Simple.NFS.GUI/raw/master/Linux/1.0.17/simple-nfs-gui_1.0.17-0ubuntu1_all.deb -P ~ && sudo dpkg -i ~/simple-nfs-gui_1.0.17-0ubuntu1_all.deb && sudo apt-get install -fy && rm ~/simple-nfs-gui_1.0.17-0ubuntu1_all.deb && sudo -H Simple_NFS_GUI
  ```

**Comment by Philippe734** [comment]
Fixed with the latest release as AppImage
