### ISSUE TITLE
Doesn't Install Correctly

### ISSUE THREAD

**Issue by KitchM** [Philippe734/Simple.NFS.GUI#25]
Attempted install on Debian 10.

There is no list of dependencies shown.  Therefore, they cannot be satisfied.

From terminal window:
 for systemd (241-7~deb10u4) ...
$ sudo add-apt-repository ppa:gambas-team/gambas3 -y && sudo apt-get update && wget https://github.com/Philippe734/Simple.NFS.GUI/raw/master/Linux/1.0.16/simple-nfs-gui_1.0.16-0ubuntu1_all.deb -P ~ && sudo dpkg -i ~/simple-nfs-gui_1.0.16-0ubuntu1_all.deb && sudo apt-get install -fy && rm ~/simple-nfs-gui_1.0.16-0ubuntu1_all.deb && sudo -H Simple_NFS_GUI
gpg: keybox '/tmp/tmpj0wrw7c2/pubring.gpg' created
gpg: /tmp/tmpj0wrw7c2/trustdb.gpg: trustdb created
gpg: key 50B027516CAEE58D: public key "Launchpad PPA for Gambas Ubuntu Maintainers" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Ign:1 http://mondo.mirror.pclark.com/ftp/pub/mondorescue/debian/10 buster InRelease
Err:2 http://mondo.mirror.pclark.com/ftp/pub/mondorescue/debian/10 buster Release                   
  404  Not Found [IP: 173.48.199.185 80]
Hit:3 https://linux.teamviewer.com/deb stable InRelease                                             
Hit:4 http://deb.debian.org/debian buster InRelease                                                 
Hit:5 https://download.jitsi.org stable/ InRelease                                                  
Ign:6 https://dl.packager.io/srv/deb/opf/openproject/dev/debian 10 InRelease                        
Hit:7 http://deb.trueconf.com/debian buster InRelease                                               
Hit:8 https://deb.leap.se/client release InRelease                                         
Get:9 https://dl.packager.io/srv/deb/opf/openproject/dev/debian 10 Release                
Ign:11 http://ppa.launchpad.net/gambas-team/gambas3/ubuntu hirsute InRelease
Err:12 http://ppa.launchpad.net/gambas-team/gambas3/ubuntu hirsute Release
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Reading package lists... Done
E: The repository 'http://mondo.mirror.pclark.com/ftp/pub/mondorescue/debian/10 buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/gambas-team/gambas3/ubuntu hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
$ sudo add-apt-repository ppa:gambas-team/gambas3 -y && sudo apt-get update && wget https://github.com/Philippe734/Simple.NFS.GUI/raw/master/Linux/1.0.17/simple-nfs-gui_1.0.17-0ubuntu1_all.deb -P ~ && sudo dpkg -i ~/simple-nfs-gui_1.0.17-0ubuntu1_all.deb && sudo apt-get install -fy && rm ~/simple-nfs-gui_1.0.17-0ubuntu1_all.deb && sudo -H Simple_NFS_GUI
gpg: keybox '/tmp/tmp6ypckzuc/pubring.gpg' created
gpg: /tmp/tmp6ypckzuc/trustdb.gpg: trustdb created
gpg: key 50B027516CAEE58D: public key "Launchpad PPA for Gambas Ubuntu Maintainers" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Hit:1 http://deb.debian.org/debian buster InRelease
Ign:2 http://mondo.mirror.pclark.com/ftp/pub/mondorescue/debian/10 buster InRelease                 
Hit:3 https://linux.teamviewer.com/deb stable InRelease                                             
Err:4 http://mondo.mirror.pclark.com/ftp/pub/mondorescue/debian/10 buster Release                   
  404  Not Found [IP: 173.48.199.185 80]
Ign:5 http://ppa.launchpad.net/gambas-team/gambas3/ubuntu hirsute InRelease                         
Hit:6 http://deb.trueconf.com/debian buster InRelease                                               
Hit:7 https://deb.leap.se/client release InRelease                                                  
Err:8 http://ppa.launchpad.net/gambas-team/gambas3/ubuntu hirsute Release                 
  404  Not Found [IP: 91.189.95.83 80]
Hit:9 https://download.jitsi.org stable/ InRelease                  
Ign:10 https://dl.packager.io/srv/deb/opf/openproject/dev/debian 10 InRelease
Get:11 https://dl.packager.io/srv/deb/opf/openproject/dev/debian 10 Release
Reading package lists... Done
E: The repository 'http://mondo.mirror.pclark.com/ftp/pub/mondorescue/debian/10 buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/gambas-team/gambas3/ubuntu hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

GDebi shows:
W: simple-nfs-gui: latest-debian-changelog-entry-without-new-version
W: simple-nfs-gui: latest-debian-changelog-entry-reuses-existing-version 1.0.15-0ubuntu1 == 1.0.15-0ubuntu1 (last used: Wed, 05 Jul 2017 12:00:00 +0000)
W: simple-nfs-gui: spelling-error-in-changelog beacuse because
W: simple-nfs-gui: copyright-without-copyright-notice
W: simple-nfs-gui: binary-without-manpage usr/bin/Simple_NFS_GUI
W: simple-nfs-gui: binary-without-manpage usr/bin/simple-nfs-gui
W: simple-nfs-gui: command-in-menu-file-and-desktop-file Simple_NFS_GUI usr/share/menu/simple-nfs-gui:4

Lintian finished with exit status 0

**Comment by pikakolendo02** [comment]
The line in tutorial
`sudo dpkg -i ~/simple-nfs-gui_1.0.16-0ubuntu1_all.deb && sudo apt-get install -fy`
seems wrong. `dpkg` doesn't return 0 after install so `apt-get` doesn't run.
It should be `;;` instead of `&&`.

**Comment by Philippe734** [comment]
Fixed with the latest release as AppImage
