### ISSUE TITLE
How to compile it from source

### ISSUE THREAD

**Issue by librewish** [Philippe734/Simple.NFS.GUI#26]
just for the info

i added the -bin ie binary version to aur

https://aur.archlinux.org/packages/simple-nfs-gui-bin/

and how do we compile it from source i did not find any instruction in readme

**Comment by librewish** [comment]
ohh it doesnt work with other distros at all due to usage of apt

so its only for ubuntu

please rename the description

Simple NFS GUI for Linux

to
Simple NFS GUI for Ubuntu only

**Comment by librewish** [comment]
okay after some search
i found how to compile it 
```
gbc3 -e -a -g -t -p -m 
gba3
```
 and fiddling with source i got it to work

i removed the apt part
and 
the command 
and changed
`hostname -I`
to 
`hostname -i`

so it works now instead of giving out of bound error

**Comment by mbnoimi** [comment]
> and how do we compile it from source i did not find any instruction in readme

I'm unable to find any source code!
It seems this repository a fake one for closed source binaries!!!

**Comment by Philippe734** [comment]
My app use the Gambas IDE to use it. Here is the source code of Gambas:
https://gitlab.com/gambas/gambas
