### ISSUE TITLE
Can't select a server

### ISSUE THREAD

**Issue by antikruk** [Philippe734/Simple.NFS.GUI#27]
Manjaro nibia

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
FMain.cmdFindMachines_Click.184: #21: Out of bounds
FMain.cmdFindMachines_Click.184 
QXcbClipboard: Unable to receive an event from the clipboard manager in a reasonable time

**Comment by griffinwebnet** [comment]
i have this identical error. was a resolution ever found?

**Comment by follwersion** [comment]
same here

**Comment by Philippe734** [comment]
Fixed with the latest release as AppImage
