### ISSUE TITLE
Ubuntu install tutorial wrong

### ISSUE THREAD

**Issue by pikakolendo02** [Philippe734/Simple.NFS.GUI#28]
The line in Ubuntu 20.04 install tutorial
`sudo dpkg -i ~/simple-nfs-gui_1.0.16-0ubuntu1_all.deb && sudo apt-get install -fy`
seems wrong. If dependences are not satisfied, `dpkg` doesn't return 0 after install so `apt-get` doesn't run.
It should be `;` instead of `&&`.

**Comment by Philippe734** [comment]
If you wish try again, I released a package as AppImage

**Comment by Philippe734** [comment]
Fixed with the latest release as AppImage
