### ISSUE TITLE
Cannot install in Kubuntu 20.10

### ISSUE THREAD

**Issue by anarchotaoist** [Philippe734/Simple.NFS.GUI#29]
ppa will not add

E: The repository 'http://ppa.launchpad.net/gambas-team/gambas3/ubuntu groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

Deb needs gamba dependencies but installing these from distro repository still sends dependency errors:

dpkg: dependency problems prevent configuration of simple-nfs-gui:
 simple-nfs-gui depends on gambas3-gb-qt4 (>= 3.14); however:
  Package gambas3-gb-qt4 is not installed.
 simple-nfs-gui depends on gambas3-gb-qt4 (<< 3.99.0); however:
  Package gambas3-gb-qt4 is not installed.

**Comment by Philippe734** [comment]
If you wish try again, I released a package as AppImage

**Comment by Philippe734** [comment]
Fixed with the latest release as AppImage
