### ISSUE TITLE
unable to run simple NFS gui on RHEL 9

### ISSUE THREAD

**Issue by ioctlsg** [Philippe734/Simple.NFS.GUI#37]
I can't run the program the error dump is as below. what am i doing wrong?

[simonong@localhost Downloads]$ ./simple-nfs-gui-gambas-latest-x86_64.AppImage 
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Extracting usr/share/icons/hicolor/32x32/apps/mapview.png to "/home/simonong/.local/share/icons/hicolor/32x32/apps/appimagekit_a1967cf1d47ed8fa3d8809d44cbefac8_mapview.png"
Extracting usr/share/mime/packages/gambas3-runtime.xml to "/home/simonong/.local/share/mime/packages/appimagekit_a1967cf1d47ed8fa3d8809d44cbefac8_gambas3-runtime.xml"
WARNING: Unable to resize the application icon into a 128x128 image: "Unable to load image.". It will be written unchanged.
WARNING: Unable to resize the application icon into a 256x256 image: "Unable to load image.". It will be written unchanged.
gtk-update-icon-cache: Cache file created successfully.
/usr/bin/which: no gtk-update-icon-cache-3.0 in (/home/simonong/.local/bin:/home/simonong/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin)
/usr/bin/which: no update-icon-caches in (/home/simonong/.local/bin:/home/simonong/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin)

(simple-nfs-gui.gambas:77150): GLib-GIO-ERROR **: 13:48:35.082: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'

**Comment by Philippe734** [comment]
Because your desktop use Wayland. I will investigate further.

**Comment by ioctlsg** [comment]
oh man.... just found out this 
https://linuxgamingcentral.com/posts/appimage-dev-rejects-wayland-support/
