### ISSUE TITLE
Setup comment and query

### ISSUE THREAD

**Issue by jzl2w8** [Philippe734/Simple.NFS.GUI#4]
Hello
I know it sounds obvious but worth mentioning in your instructions after setting up the repository connection to download the package use:
$ sudo apt-get simple-nfs-gui
The precise name of the application confused me.
Unfortunately I still then had problems running the application, I tried to launch it from the GUI and it said that it needs root access.  I couldn’t easily work out how to launch the app from the GUI or from a command shell as root.  Possibly a newbie question but how do you launch it as sudo/root.  If you can please include in your instructions. 
Thanks.

**Comment by ozett** [comment]
shouldnt it be with "install"-option like:

$sudo apt-get INSTALL simple-nfs-gui

**Comment by ozett** [comment]
maybe it should also be mentioned to start it afterwares (from /usr/bin) with:

$ Simple_NFS_GUI

**Comment by Philippe734** [comment]
Currently, you can not install the app with **$sudo apt-get INSTALL simple-nfs-gui** because the app is not in the PPA provided. To install the app, we need to install the deb package (after add the PPA).
I'm ready to modify the instructiosn, what are your suggestion ?
