### ISSUE TITLE
GUI not starting at Ubuntu 17.10

### ISSUE THREAD

**Issue by PRIHLOP** [Philippe734/Simple.NFS.GUI#8]
My OS:
cat /etc/lsb-release 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
```

After click on icon "Simple NFS GUI" happening is nothing.
String from /var/log/syslog:

`kernel: [575808.921821] gbr3[25746]: segfault at 198 ip 00007f4421e8280a sp 00007ffe73cdeb80 error 4 in libX11.so.6.3.0[7f4421e5a000+134000]`

**Comment by Philippe734** [comment]
You need to run it as root. It works fine on Ubuntu 18.04:
![image](https://user-images.githubusercontent.com/24923693/39833304-f978dc4a-53c9-11e8-911a-b53e86bdd60b.png)
